language: ruby
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
rvm:
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.2
  - 3.0.0-preview2
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_6.1.gemfile
matrix:
  exclude:
    - rvm: 2.4.10
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/rails_6.1.gemfile
jobs:
  allow_failures:
    - rvm: 3.0.0-preview2
